# Generated by Django 3.2.8 on 2022-07-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('fullnames', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('timess', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('DEPT', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('emails', models.EmailField(max_length=100)),
                ('contacts', models.CharField(max_length=100)),
                ('passwords', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('users', models.CharField(max_length=100)),
            ],
        ),
    ]
